### ISSUE TITLE
Unable to persist entity.

### ISSUE THREAD

**Issue by vishalsharma29** [kuros/random-jpa#49]
Getting below exception while persisting:
**java.lang.IllegalArgumentException: Could not resolve NativeQuery parameter type**

Full Stacktrace:

java.lang.IllegalArgumentException: Could not resolve NativeQuery parameter type : `org.hibernate.query.internal.QueryParameterPositionalImpl@20`
 
	at org.hibernate.sql.exec.internal.JdbcParameterBindingsImpl.<init>(JdbcParameterBindingsImpl.java:78)
	at org.hibernate.query.sql.internal.NativeSelectQueryPlanImpl.performList(NativeSelectQueryPlanImpl.java:123)
	at org.hibernate.query.sql.internal.NativeQueryImpl.doList(NativeQueryImpl.java:628)
	at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:136)
	at org.hibernate.query.Query.getResultList(Query.java:120)
	at com.github.kuros.random.jpa.persistor.hepler.Finder.findByAttributes(Finder.java:138)
	at com.github.kuros.random.jpa.resolver.PersistedEntityResolverImpl.findObject(PersistedEntityResolverImpl.java:150)
	at com.github.kuros.random.jpa.resolver.PersistedEntityResolverImpl.loadParentDetails(PersistedEntityResolverImpl.java:135)
	at com.github.kuros.random.jpa.resolver.PersistedEntityResolverImpl.loadParentDetails(PersistedEntityResolverImpl.java:138)
	at com.github.kuros.random.jpa.resolver.PersistedEntityResolverImpl.loadPersistedObjectByIds(PersistedEntityResolverImpl.java:67)
	at com.github.kuros.random.jpa.persistor.EntityPersistorImpl.getClassIndexObjectMap(EntityPersistorImpl.java:76)
	at com.github.kuros.random.jpa.persistor.EntityPersistorImpl.persist(EntityPersistorImpl.java:66)
	at com.github.kuros.random.jpa.JPAContextImpl.persist(JPAContextImpl.java:76)
	at com.cobalt.dap.random.jpa.generator.BaseContext.persist(BaseContext.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:244)
	at jdk.proxy2/jdk.proxy2.$Proxy198.persist(Unknown Source)
	at com.cobalt.dap.channel.data.service.impl.progressus.ProgressusCampaignDataServiceImplTest.shouldGetCampaignInfo(ProgressusCampaignDataServiceImplTest.java:239)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by kuros** [comment]
Fixed with v2.0.2
